// This files holds just the request and response definitions for general LaaS clients.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: laas/v1/public_api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PublicAPI_ListAvailableVendors_FullMethodName = "/laas.v1.PublicAPI/ListAvailableVendors"
	PublicAPI_GetSingleVendor_FullMethodName      = "/laas.v1.PublicAPI/GetSingleVendor"
	PublicAPI_GetVendorsByIds_FullMethodName      = "/laas.v1.PublicAPI/GetVendorsByIds"
)

// PublicAPIClient is the client API for PublicAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicAPIClient interface {
	// Retrieve all available vendors based on customer location and filtering.
	ListAvailableVendors(ctx context.Context, in *ListAvailableVendorsRequest, opts ...grpc.CallOption) (*ListAvailableVendorsResponse, error)
	// Retrieve availability, delivery fee and time estimate for a single vendor.
	GetSingleVendor(ctx context.Context, in *GetSingleVendorRequest, opts ...grpc.CallOption) (*GetSingleVendorResponse, error)
	// Retrieve availability for selected vendors.
	GetVendorsByIds(ctx context.Context, in *GetVendorsByIdsRequest, opts ...grpc.CallOption) (*GetVendorsByIdsResponse, error)
}

type publicAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicAPIClient(cc grpc.ClientConnInterface) PublicAPIClient {
	return &publicAPIClient{cc}
}

func (c *publicAPIClient) ListAvailableVendors(ctx context.Context, in *ListAvailableVendorsRequest, opts ...grpc.CallOption) (*ListAvailableVendorsResponse, error) {
	out := new(ListAvailableVendorsResponse)
	err := c.cc.Invoke(ctx, PublicAPI_ListAvailableVendors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) GetSingleVendor(ctx context.Context, in *GetSingleVendorRequest, opts ...grpc.CallOption) (*GetSingleVendorResponse, error) {
	out := new(GetSingleVendorResponse)
	err := c.cc.Invoke(ctx, PublicAPI_GetSingleVendor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) GetVendorsByIds(ctx context.Context, in *GetVendorsByIdsRequest, opts ...grpc.CallOption) (*GetVendorsByIdsResponse, error) {
	out := new(GetVendorsByIdsResponse)
	err := c.cc.Invoke(ctx, PublicAPI_GetVendorsByIds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicAPIServer is the server API for PublicAPI service.
// All implementations must embed UnimplementedPublicAPIServer
// for forward compatibility
type PublicAPIServer interface {
	// Retrieve all available vendors based on customer location and filtering.
	ListAvailableVendors(context.Context, *ListAvailableVendorsRequest) (*ListAvailableVendorsResponse, error)
	// Retrieve availability, delivery fee and time estimate for a single vendor.
	GetSingleVendor(context.Context, *GetSingleVendorRequest) (*GetSingleVendorResponse, error)
	// Retrieve availability for selected vendors.
	GetVendorsByIds(context.Context, *GetVendorsByIdsRequest) (*GetVendorsByIdsResponse, error)
	mustEmbedUnimplementedPublicAPIServer()
}

// UnimplementedPublicAPIServer must be embedded to have forward compatible implementations.
type UnimplementedPublicAPIServer struct {
}

func (UnimplementedPublicAPIServer) ListAvailableVendors(context.Context, *ListAvailableVendorsRequest) (*ListAvailableVendorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableVendors not implemented")
}
func (UnimplementedPublicAPIServer) GetSingleVendor(context.Context, *GetSingleVendorRequest) (*GetSingleVendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingleVendor not implemented")
}
func (UnimplementedPublicAPIServer) GetVendorsByIds(context.Context, *GetVendorsByIdsRequest) (*GetVendorsByIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVendorsByIds not implemented")
}
func (UnimplementedPublicAPIServer) mustEmbedUnimplementedPublicAPIServer() {}

// UnsafePublicAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicAPIServer will
// result in compilation errors.
type UnsafePublicAPIServer interface {
	mustEmbedUnimplementedPublicAPIServer()
}

func RegisterPublicAPIServer(s grpc.ServiceRegistrar, srv PublicAPIServer) {
	s.RegisterService(&PublicAPI_ServiceDesc, srv)
}

func _PublicAPI_ListAvailableVendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableVendorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).ListAvailableVendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicAPI_ListAvailableVendors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).ListAvailableVendors(ctx, req.(*ListAvailableVendorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_GetSingleVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSingleVendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).GetSingleVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicAPI_GetSingleVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).GetSingleVendor(ctx, req.(*GetSingleVendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_GetVendorsByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendorsByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).GetVendorsByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicAPI_GetVendorsByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).GetVendorsByIds(ctx, req.(*GetVendorsByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicAPI_ServiceDesc is the grpc.ServiceDesc for PublicAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "laas.v1.PublicAPI",
	HandlerType: (*PublicAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAvailableVendors",
			Handler:    _PublicAPI_ListAvailableVendors_Handler,
		},
		{
			MethodName: "GetSingleVendor",
			Handler:    _PublicAPI_GetSingleVendor_Handler,
		},
		{
			MethodName: "GetVendorsByIds",
			Handler:    _PublicAPI_GetVendorsByIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "laas/v1/public_api.proto",
}
